[2025-04-20T17:34:18.977+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-20T17:34:19.002+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: supply_chain_dag.collect_data manual__2025-04-20T17:34:17.209387+00:00 [queued]>
[2025-04-20T17:34:19.016+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: supply_chain_dag.collect_data manual__2025-04-20T17:34:17.209387+00:00 [queued]>
[2025-04-20T17:34:19.016+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-20T17:34:19.036+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): collect_data> on 2025-04-20 17:34:17.209387+00:00
[2025-04-20T17:34:19.045+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=971) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-20T17:34:19.047+0000] {standard_task_runner.py:72} INFO - Started process 972 to run task
[2025-04-20T17:34:19.048+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'supply_chain_dag', 'collect_data', 'manual__2025-04-20T17:34:17.209387+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/supply_chain_dag.py', '--cfg-path', '/tmp/tmped19qh7g']
[2025-04-20T17:34:19.050+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask collect_data
[2025-04-20T17:34:19.114+0000] {task_command.py:467} INFO - Running <TaskInstance: supply_chain_dag.collect_data manual__2025-04-20T17:34:17.209387+00:00 [running]> on host 4eea4bee2aed
[2025-04-20T17:34:19.248+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='supply_chain_dag' AIRFLOW_CTX_TASK_ID='collect_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-20T17:34:17.209387+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-20T17:34:17.209387+00:00'
[2025-04-20T17:34:19.250+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-20T17:34:19.294+0000] {logging_mixin.py:190} INFO - {'status': 'Data sent to Kafka', 'data': {'order_id': 'ORD-5B9A1F4F', 'departure_date': '2025-04-15', 'arrival_date': '2025-04-22', 'quantity': 378, 'warehouse': 'WH2', 'destination': 'DistributionCenter', 'shipping_mode': 'Standard Class', 'order_amount': 205.01, 'customer_id': 'CUST-A852EE2C', 'late_delivery_risk': 0}}
[2025-04-20T17:34:19.295+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-20T17:34:19.314+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-20T17:34:19.315+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=supply_chain_dag, task_id=collect_data, run_id=manual__2025-04-20T17:34:17.209387+00:00, execution_date=20250420T173417, start_date=20250420T173419, end_date=20250420T173419
[2025-04-20T17:34:19.424+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-20T17:34:19.450+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-20T17:34:19.452+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
